### PR TITLE
Sync upstream

### PR DESCRIPTION
**Pull request by tuxuser**

### CODE REVIEW

**Comment by IntelOrca** [comment]
What is your intention?

**Comment by tuxuser** [comment]
Get an updated NuGet package ;)

**Comment by IntelOrca** [comment]
I don't think this repo is necessary anymore. The upstream has automatic CI to nuget. See https://www.nuget.org/packages/SDL2-CS-Rolling/

**Comment by tuxuser** [comment]
You are right, thanks for the info!

**Pull request closed without merging**
